/** Loader and helpers for `test/fixtures/registry.json` (generated by `go run ./tools/fixturegen/registry`). */
import { asString, isJsonObject, type Json, type JsonObject } from "../../src/json/index.ts";
import {
  type ModelCatalogs,
  embeddedCatalogs,
  sectionModels,
  type Section,
} from "../../src/registry/catalog.ts";
import type { ClientProjection } from "../../src/registry/availability.ts";
import { decodeWireModel, fromWire, type ModelInfo } from "../../src/registry/model-info.ts";
import { type ClientRegistration, ModelRegistryIndex } from "../../src/registry/registry.ts";
import raw from "../fixtures/registry.json?raw";

export interface FixtureClient {
  readonly id: string;
  readonly provider: string;
  readonly section?: Section;
  readonly models?: ReadonlyArray<Json>;
}

export interface FixtureEvent {
  readonly op: "quota" | "suspend";
  readonly client: string;
  readonly model: string;
  readonly reason?: string;
}

export interface FixtureRequest {
  readonly name: string;
  readonly path: string;
  readonly headers?: Record<string, string>;
  readonly status: number;
  readonly body: string;
}

export interface InfoQuery {
  readonly model: string;
  readonly provider: string;
  readonly info: Json;
}

export interface FixtureScenario {
  readonly name: string;
  readonly clients: ReadonlyArray<FixtureClient>;
  readonly events?: ReadonlyArray<FixtureEvent>;
  readonly disableCloaking?: boolean;
  readonly requests: ReadonlyArray<FixtureRequest>;
  readonly codexClient: ReadonlyArray<{
    readonly variant: string;
    readonly version: string;
    readonly status: number;
    readonly size: number;
    readonly sha256: string;
    readonly entries: Record<string, string>;
    readonly models: ReadonlyArray<Record<string, unknown>> | null;
  }>;
  readonly registry: {
    readonly providers: Record<string, string[]>;
    readonly infos: ReadonlyArray<InfoQuery>;
    readonly lookups: ReadonlyArray<InfoQuery>;
    readonly available: ReadonlyArray<Json>;
    readonly first: string;
  };
}

export interface RegistryFixture {
  readonly generatedAt: number;
  readonly sections: Record<string, ReadonlyArray<Json>>;
  readonly scenarios: ReadonlyArray<FixtureScenario>;
}

export const fixture: RegistryFixture = JSON.parse(raw) as RegistryFixture;

export const catalogs: ModelCatalogs = embeddedCatalogs();

export const fromGo = (wire: Json): ModelInfo => fromWire(decodeWireModel(wire));

/** Drops Go zero values (`omitempty`) so records from different decoders compare equal. */
export const canon = (value: Json | undefined): Json | undefined => {
  if (Array.isArray(value))
    return value.length === 0 ? undefined : value.map((entry) => canon(entry) ?? null);

  if (value !== null && typeof value === "object") {
    const out: JsonObject = {};

    for (const [key, entry] of Object.entries(value).toSorted(([a], [b]) => (a < b ? -1 : 1))) {
      const next = canon(entry);

      if (next !== undefined) out[key] = next;
    }

    return Object.keys(out).length === 0 ? undefined : out;
  }

  return value === false || value === 0 || value === "" || value === null ? undefined : value;
};

/** `canon` of any JSON-serialisable record (model infos, specs); `undefined` stays `undefined`. */
export const canonOf = <T>(value: T): Json | undefined =>
  value === undefined ? undefined : canon(JSON.parse(JSON.stringify(value)));

/** Fixture time: one minute after the quota/suspension events were recorded. */
export const fixtureNow = (): number => fixture.generatedAt + 60_000;

export const scenarioClients = (scenario: FixtureScenario): ClientRegistration[] =>
  scenario.clients.map((client) => {
    const models =
      client.section !== undefined
        ? sectionModels(catalogs, client.section)
        : (client.models ?? []).map((model) => fromGo(model));

    const events = (scenario.events ?? []).filter((event) => event.client === client.id);

    const projection = (model: ModelInfo): ClientProjection | undefined => {
      const mine = events.filter((event) => event.model === model.id);

      if (mine.length === 0) return undefined;
      const suspend = mine.find((event) => event.op === "suspend");
      const quota = mine.some((event) => event.op === "quota");

      return {
        suspended: suspend !== undefined,
        suspendReason: suspend?.reason ?? "",
        quotaExceeded: quota,
        quotaSince: fixture.generatedAt,
      };
    };

    return { id: client.id, provider: client.provider, models, projection };
  });

export const scenarioIndex = (scenario: FixtureScenario): ModelRegistryIndex =>
  new ModelRegistryIndex(scenarioClients(scenario), fixtureNow());

/** Sorts the entries of the named arrays by `key`, for comparing Go bodies whose order is map-iteration order. */
export const sortedBody = (body: string, sort: Record<string, string>): Json => {
  const parsed = JSON.parse(body) as JsonObject;

  for (const [field, key] of Object.entries(sort)) {
    const list = parsed[field];

    if (Array.isArray(list)) {
      list.sort((a, b) => {
        const left = asString(isJsonObject(a) ? a[key] : undefined);
        const right = asString(isJsonObject(b) ? b[key] : undefined);

        return left < right ? -1 : left > right ? 1 : 0;
      });
    }
  }

  return parsed;
};
