/**
 * Loader and helpers for the thinking golden fixtures generated by `go run ./tools/fixturegen/thinking`.
 */
import { type Json, tryParseJson } from "../../src/json/index.ts"
import type { ModelInfoLookup, SummaryConfig, ThinkingConfig, ThinkingModelInfo } from "../../src/thinking/index.ts"
import raw from "../fixtures/thinking.json?raw"

export interface ModelSpec extends ThinkingModelInfo {
  readonly id: string
}

export interface SummaryJson {
  readonly mode: SummaryConfig["mode"]
  readonly detail: string
}

export interface ApplyFixture {
  readonly name?: string
  readonly variant: "plain" | "summary" | "source" | "modelInfo" | "modelInfoSummary"
  readonly body: string
  readonly source?: string
  readonly model: string
  readonly from: string
  readonly to: string
  readonly providerKey: string
  readonly modelInfo?: ModelSpec | null
  readonly modelRef?: string
  readonly summary?: SummaryJson
  readonly normalizedUpdatesChanged?: boolean
  readonly out?: string
  readonly same?: boolean
  readonly error?: { readonly code: string; readonly message: string }
}

export interface Fixture {
  readonly catalog: Record<string, ModelSpec>
  readonly synthetic: Record<string, ModelSpec>
  readonly suffix: ReadonlyArray<{
    readonly input: string
    readonly modelName: string
    readonly hasSuffix: boolean
    readonly rawSuffix: string
    readonly numericOk: boolean
    readonly numeric: number
    readonly specialOk: boolean
    readonly special: string
    readonly levelOk: boolean
    readonly level: string
    readonly effort: string
  }>
  readonly convert: {
    readonly levelToBudget: ReadonlyArray<{ level: string; ok: boolean; budget: number }>
    readonly budgetToLevel: ReadonlyArray<{ budget: number; ok: boolean; level: string }>
    readonly claudeEffort: ReadonlyArray<{ level: string; supportsMax: boolean; ok: boolean; effort: string }>
    readonly hasLevel: ReadonlyArray<{ levels: string[] | null; target: string; result: boolean }>
  }
  readonly validate: ReadonlyArray<{
    readonly model: ModelSpec | null
    readonly cases: ReadonlyArray<{ c: string; f: string; t: string; s?: boolean; o?: string; e?: string }>
  }>
  readonly apply: readonly ApplyFixture[]
  readonly applier: ReadonlyArray<{
    applier: string
    model?: string
    config: string
    body: string
    out?: string
    same?: boolean
    error?: string
  }>
  readonly summaryExtract: ReadonlyArray<{
    format: string
    target: string
    body: string
    summary: SummaryJson
    explicit: SummaryJson
    translated: SummaryJson
  }>
  readonly summaryApply: ReadonlyArray<{
    kind: "plain" | "model" | "translated"
    format: string
    model?: string
    body: string
    source?: string
    config: SummaryJson
    out?: string
    same?: boolean
  }>
  readonly strip: ReadonlyArray<{ provider: string; body: string; out?: string; same?: boolean }>
  readonly text: ReadonlyArray<{ part: string; text: string }>
  readonly usage: ReadonlyArray<{ provider: string; model: string; body: string; request: string; translated: string }>
}

export const fixture = JSON.parse(raw) as Fixture

/** `registry.LookupModelInfo` over the static catalog dumped from Go (provider-independent). */
export const catalogLookup: ModelInfoLookup = (modelId) => fixture.catalog[modelId]

/** Parses fixture JSON text; unparsable text (a Go "invalid body") becomes `undefined`. */
export const parseBody = (text: string): Json | undefined => tryParseJson(text)

/** Order-sensitive comparison key; `undefined` for an unparsable body. */
export const bodyKey = (body: Json | undefined): string => (body === undefined ? "<invalid>" : JSON.stringify(body))

export const expectedKey = (text: string): string => bodyKey(parseBody(text))

/** Compact config encoding shared with the Go generator: `none`, `auto`, `budget:N`, `level:X`. */
export const encodeConfig = (c: ThinkingConfig): string => {
  switch (c.mode) {
    case "budget":
      return `budget:${c.budget}`
    case "level":
      return `level:${c.level}`
    case "none":
      return c.budget !== 0 || c.level !== "" ? `none:${c.budget}:${c.level}` : "none"
    case "auto":
      return c.budget !== -1 || c.level !== "" ? `auto:${c.budget}:${c.level}` : "auto"
  }
}

export const decodeConfig = (text: string): ThinkingConfig => {
  const [mode, ...rest] = text.split(":")
  const value = rest.join(":")
  switch (mode) {
    case "budget":
      return { mode: "budget", budget: Number(value), level: "" }
    case "level":
      return { mode: "level", budget: 0, level: value }
    case "none":
      return { mode: "none", budget: 0, level: "" }
    default:
      return { mode: "auto", budget: -1, level: "" }
  }
}

/** Resolves a model key of the `applier` section: synthetic id, `catalog:<id>` or empty (no model info). */
export const resolveApplierModel = (key: string | undefined): ModelSpec | undefined => {
  if (key === undefined || key === "") return undefined
  if (key.startsWith("catalog:")) return fixture.catalog[key.slice("catalog:".length)]
  return fixture.synthetic[key]
}

/** Lossless `mode|budget|level` config form used by the `applier` section. */
export const decodeFullConfig = (text: string): ThinkingConfig => {
  const [mode, budget, ...level] = text.split("|")
  return { mode: mode as ThinkingConfig["mode"], budget: Number(budget), level: level.join("|") }
}

/** Runs `check` over `cases`, returning at most `limit` failure descriptions. */
export const collectMismatches = <T>(
  cases: Iterable<T>,
  check: (testCase: T) => string | undefined,
  limit = 8
): string[] => {
  const failures: string[] = []
  for (const testCase of cases) {
    const failure = check(testCase)
    if (failure !== undefined) {
      failures.push(failure)
      if (failures.length >= limit) break
    }
  }
  return failures
}
